[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "llama-index-tools-olostep"
version = "0.1.1"
description = "llama-index tools olostep integration"
authors = [{name = "Olostep"}]
requires-python = ">=3.9,<4.0"
readme = "README.md"
license = "MIT"
keywords = ["olostep", "web scraping", "web crawling", "web search", "data extraction"]
dependencies = [
    "llama-index-core>=0.11.0",
    "olostep",
]

[project.urls]
Homepage = "https://www.olostep.com"
Repository = "https://github.com/olostep-api/llama-index-tools-olostep"

[tool.llamahub]
contains-example = false
import-path = "llama_index.tools.olostep"

[tool.llamahub.class-authors]
OlostepToolSpec = "olostep"

[tool.hatch.build.targets.sdist]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.hatch.build.targets.wheel]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[dependency-groups]
dev = [
    "pytest>=7.2.1",
    "pytest-mock>=3.11.1",
]