python_tests(
    name="tests",
    dependencies=["llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/__init__.py", "llama-index-integrations/readers/llama-index-readers-gcs:poetry"],
)

python_requirement(
    name="gcsfs",
    requirements=["gcsfs>=2023.12.2"],
)
