python_tests(
    interpreter_constraints=[">=3.10"],
    dependencies=["llama-index-integrations/selectors/llama-index-selectors-notdiamond:poetry#litellm"],
)

python_test_utils(
    name="test_utils",
)
