python_tests(
    dependencies=[
        'llama-index-integrations/llms/llama-index-llms-modelscope:poetry#sentencepiece',
        'llama-index-integrations/llms/llama-index-llms-modelscope:poetry#ms-swift',
    ],
)
