# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python docs/merge_llama_deploy_docs.py

mkdocs:
  configuration: docs/mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
