# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - python -m pip install poetry
    post_install:
      - cd docs && poetry config virtualenvs.create false && poetry install --no-root
    pre_build:
      - cd docs && poetry run merge-llama-deploy-docs

mkdocs:
  configuration: docs/mkdocs.yml

python:
  install:
    - method: pip
      path: docs
