python_sources()

python_tests(
    name="tests",
    dependencies=[
        "llama-index-core/tests/indices/query/query_transform/__init__.py",
        "llama-index-core/tests/indices/query/query_transform:query_transform",
    ],
)
