python_test_utils(
    name="test_utils",
    dependencies=[
        "llama-index-core/tests/indices/vector_store/mock_services.py",
        "llama-index-core/tests/indices/list/__init__.py",
        "llama-index-core/tests/indices/list:list",
        "llama-index-core/tests/mock_utils/mock_predict.py",
        "llama-index-core/tests/mock_utils/mock_text_splitter.py",
        "llama-index-core/tests/mock_utils/mock_prompts.py",
        "llama-index-core/tests/mock_utils/mock_utils.py",
        "llama-index-core:poetry#eval-type-backport",
        "llama-index-core:poetry#platformdirs",
    ],
)

python_tests()
