poetry_requirements(
    name="poetry",
    module_mapping={"llama-index-readers-file": ["llama_index.readers.file"]}
)

python_requirements(
    name="reqs",
)

python_requirement(
    name="s3fs",
    requirements=["s3fs>=2024.3.0"],
)
