poetry_requirements(
    name="poetry",
)

python_requirement(
   requirements=[],
   dependencies=["!llama-index-core:poetry#langchain","!llama-index-integrations/llms/llama-index-llms-cohere:poetry#cohere"]
)
