load("//bazel/rules/python:pytest.bzl", "llama_pytest_test")

llama_pytest_test(
    name = "multi_modal_llms_bedrock_test",
    srcs = ["test_multi_modal_llms_bedrock.py"],
    deps = [
        "//llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock",
    ],
) 