# This file was auto-generated by Fern from our API Definition.

import typing

from .data_source_create_component_one import DataSourceCreateComponentOne

DataSourceCreateComponent = typing.Union[
    typing.Dict[str, typing.Any], DataSourceCreateComponentOne
]
