[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "llama-index-retriever-data-intelligence"
version = "0.0.1"
description = "llama-index retriever data intelligence integration"
readme = "README.md"
requires-python = ">=3.11.2,<4.0"
authors = [{name = "HPE"}]
dependencies = [
    "pydi-client>=1.0.0",
    "llama-index-core>=0.12.35",
]

[dependency-groups]
dev = [
    "pytest==7.2.1",
    "pytest-mock==3.11.1"
]

[tool.codespell]
check-filenames = true
check-hidden = true
skip = "*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt,*.ipynb"

[tool.hatch.build.targets.sdist]
include = ["llama_index/"]

[tool.hatch.build.targets.wheel]
include = ["llama_index/"]

[tool.mypy]
disallow_untyped_defs = true
exclude = ["_static", "build", "examples", "notebooks", "venv"]
ignore_missing_imports = true
python_version = "3.11.2"
