poetry_requirements(
    name="poetry",
    module_mapping={"google-api-python-client": ["googleapiclient"], "google-auth-oauthlib": ["google_auth_oauthlib"]}
)

python_requirements(
    name="reqs",
)

python_sources(
    name="python310_target",
    interpreter_constraints=[">=3.10"],
)
