name: LlamaParse Bug Report
description: File a bug report
title: "[LlamaParse]: "
labels: ["bug", "triage", "llamaparse"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please complete the following form to help us assist you.
  - type: textarea
    id: what-happened
    attributes:
      label: Bug Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Which steps should someone take to run into the same error?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Screenshots
      description: Please copy and paste any relevant screenshot.
      render: shell
