python_tests(
    dependencies=[
        "llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml:poetry#tantivy",
        "llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml:poetry#pylance",
    ],
)

python_test_utils(
    name="test_utils",
)
