python_tests(
    dependencies=["llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml:poetry#tantivy"],
    interpreter_constraints=["==3.9.*", "==3.10.*"]
)

python_test_utils(
    name="test_utils",
)
