"""
Country configuration mapping for geotargeting.

Maps ISO 3166-1 alpha-2 country codes to locale and timezone settings
for browser context configuration with Massive proxy.
"""

# Configuration for browser localization based on country code
COUNTRY_CONFIG = {
    # A
    "AF": {"locale": "fa-AF", "timezone": "Asia/Kabul"},
    "AX": {"locale": "sv-AX", "timezone": "Europe/Mariehamn"},
    "AL": {"locale": "sq-AL", "timezone": "Europe/Tirane"},
    "DZ": {"locale": "ar-DZ", "timezone": "Africa/Algiers"},
    "AS": {"locale": "en-AS", "timezone": "Pacific/Pago_Pago"},
    "AD": {"locale": "ca-AD", "timezone": "Europe/Andorra"},
    "AO": {"locale": "pt-AO", "timezone": "Africa/Luanda"},
    "AI": {"locale": "en-AI", "timezone": "America/Anguilla"},
    "AQ": {"locale": "en-AQ", "timezone": "Antarctica/McMurdo"},
    "AG": {"locale": "en-AG", "timezone": "America/Antigua"},
    "AR": {"locale": "es-AR", "timezone": "America/Argentina/Buenos_Aires"},
    "AM": {"locale": "hy-AM", "timezone": "Asia/Yerevan"},
    "AW": {"locale": "nl-AW", "timezone": "America/Aruba"},
    "AU": {"locale": "en-AU", "timezone": "Australia/Sydney"},
    "AT": {"locale": "de-AT", "timezone": "Europe/Vienna"},
    "AZ": {"locale": "az-AZ", "timezone": "Asia/Baku"},
    # B
    "BS": {"locale": "en-BS", "timezone": "America/Nassau"},
    "BH": {"locale": "ar-BH", "timezone": "Asia/Bahrain"},
    "BD": {"locale": "bn-BD", "timezone": "Asia/Dhaka"},
    "BB": {"locale": "en-BB", "timezone": "America/Barbados"},
    "BY": {"locale": "be-BY", "timezone": "Europe/Minsk"},
    "BE": {"locale": "fr-BE", "timezone": "Europe/Brussels"},
    "BZ": {"locale": "en-BZ", "timezone": "America/Belize"},
    "BJ": {"locale": "fr-BJ", "timezone": "Africa/Porto-Novo"},
    "BM": {"locale": "en-BM", "timezone": "Atlantic/Bermuda"},
    "BT": {"locale": "dz-BT", "timezone": "Asia/Thimphu"},
    "BO": {"locale": "es-BO", "timezone": "America/La_Paz"},
    "BQ": {"locale": "nl-BQ", "timezone": "America/Kralendijk"},
    "BA": {"locale": "bs-BA", "timezone": "Europe/Sarajevo"},
    "BW": {"locale": "en-BW", "timezone": "Africa/Gaborone"},
    "BV": {"locale": "en-BV", "timezone": "Antarctica/McMurdo"},
    "BR": {"locale": "pt-BR", "timezone": "America/Sao_Paulo"},
    "IO": {"locale": "en-IO", "timezone": "Indian/Chagos"},
    "BN": {"locale": "ms-BN", "timezone": "Asia/Brunei"},
    "BG": {"locale": "bg-BG", "timezone": "Europe/Sofia"},
    "BF": {"locale": "fr-BF", "timezone": "Africa/Ouagadougou"},
    "BI": {"locale": "fr-BI", "timezone": "Africa/Bujumbura"},
    # C
    "KH": {"locale": "km-KH", "timezone": "Asia/Phnom_Penh"},
    "CM": {"locale": "fr-CM", "timezone": "Africa/Douala"},
    "CA": {"locale": "en-CA", "timezone": "America/Toronto"},
    "CV": {"locale": "pt-CV", "timezone": "Atlantic/Cape_Verde"},
    "KY": {"locale": "en-KY", "timezone": "America/Cayman"},
    "CF": {"locale": "fr-CF", "timezone": "Africa/Bangui"},
    "TD": {"locale": "fr-TD", "timezone": "Africa/Ndjamena"},
    "CL": {"locale": "es-CL", "timezone": "America/Santiago"},
    "CN": {"locale": "zh-CN", "timezone": "Asia/Shanghai"},
    "CX": {"locale": "en-CX", "timezone": "Indian/Christmas"},
    "CC": {"locale": "en-CC", "timezone": "Indian/Cocos"},
    "CO": {"locale": "es-CO", "timezone": "America/Bogota"},
    "KM": {"locale": "ar-KM", "timezone": "Indian/Comoro"},
    "CG": {"locale": "fr-CG", "timezone": "Africa/Brazzaville"},
    "CD": {"locale": "fr-CD", "timezone": "Africa/Kinshasa"},
    "CK": {"locale": "en-CK", "timezone": "Pacific/Rarotonga"},
    "CR": {"locale": "es-CR", "timezone": "America/Costa_Rica"},
    "CI": {"locale": "fr-CI", "timezone": "Africa/Abidjan"},
    "HR": {"locale": "hr-HR", "timezone": "Europe/Zagreb"},
    "CU": {"locale": "es-CU", "timezone": "America/Havana"},
    "CW": {"locale": "nl-CW", "timezone": "America/Curacao"},
    "CY": {"locale": "el-CY", "timezone": "Asia/Nicosia"},
    "CZ": {"locale": "cs-CZ", "timezone": "Europe/Prague"},
    # D
    "DK": {"locale": "da-DK", "timezone": "Europe/Copenhagen"},
    "DJ": {"locale": "fr-DJ", "timezone": "Africa/Djibouti"},
    "DM": {"locale": "en-DM", "timezone": "America/Dominica"},
    "DO": {"locale": "es-DO", "timezone": "America/Santo_Domingo"},
    # E
    "EC": {"locale": "es-EC", "timezone": "America/Guayaquil"},
    "EG": {"locale": "ar-EG", "timezone": "Africa/Cairo"},
    "SV": {"locale": "es-SV", "timezone": "America/El_Salvador"},
    "GQ": {"locale": "es-GQ", "timezone": "Africa/Malabo"},
    "ER": {"locale": "ti-ER", "timezone": "Africa/Asmara"},
    "EE": {"locale": "et-EE", "timezone": "Europe/Tallinn"},
    "ET": {"locale": "am-ET", "timezone": "Africa/Addis_Ababa"},
    # F
    "FK": {"locale": "en-FK", "timezone": "Atlantic/Stanley"},
    "FJ": {"locale": "en-FJ", "timezone": "Pacific/Fiji"},
    "FI": {"locale": "fi-FI", "timezone": "Europe/Helsinki"},
    "FR": {"locale": "fr-FR", "timezone": "Europe/Paris"},
    # G
    "GF": {"locale": "fr-GF", "timezone": "America/Cayenne"},
    "PF": {"locale": "fr-PF", "timezone": "Pacific/Tahiti"},
    "TF": {"locale": "fr-TF", "timezone": "Indian/Kerguelen"},
    "GA": {"locale": "fr-GA", "timezone": "Africa/Libreville"},
    "GM": {"locale": "en-GM", "timezone": "Africa/Banjul"},
    "GE": {"locale": "ka-GE", "timezone": "Asia/Tbilisi"},
    "DE": {"locale": "de-DE", "timezone": "Europe/Berlin"},
    "GH": {"locale": "en-GH", "timezone": "Africa/Accra"},
    "GI": {"locale": "en-GI", "timezone": "Europe/Gibraltar"},
    "GR": {"locale": "el-GR", "timezone": "Europe/Athens"},
    "GL": {"locale": "kl-GL", "timezone": "America/Godthab"},
    "GD": {"locale": "en-GD", "timezone": "America/Grenada"},
    "GP": {"locale": "fr-GP", "timezone": "America/Guadeloupe"},
    "GU": {"locale": "en-GU", "timezone": "Pacific/Guam"},
    "GT": {"locale": "es-GT", "timezone": "America/Guatemala"},
    "GG": {"locale": "en-GG", "timezone": "Europe/Guernsey"},
    "GN": {"locale": "fr-GN", "timezone": "Africa/Conakry"},
    "GW": {"locale": "pt-GW", "timezone": "Africa/Bissau"},
    "GY": {"locale": "en-GY", "timezone": "America/Guyana"},
    # H
    "HT": {"locale": "fr-HT", "timezone": "America/Port-au-Prince"},
    "HM": {"locale": "en-HM", "timezone": "Indian/Kerguelen"},
    "VA": {"locale": "it-VA", "timezone": "Europe/Vatican"},
    "HN": {"locale": "es-HN", "timezone": "America/Tegucigalpa"},
    "HK": {"locale": "zh-HK", "timezone": "Asia/Hong_Kong"},
    "HU": {"locale": "hu-HU", "timezone": "Europe/Budapest"},
    # I
    "IS": {"locale": "is-IS", "timezone": "Atlantic/Reykjavik"},
    "IN": {"locale": "hi-IN", "timezone": "Asia/Kolkata"},
    "ID": {"locale": "id-ID", "timezone": "Asia/Jakarta"},
    "IR": {"locale": "fa-IR", "timezone": "Asia/Tehran"},
    "IQ": {"locale": "ar-IQ", "timezone": "Asia/Baghdad"},
    "IE": {"locale": "en-IE", "timezone": "Europe/Dublin"},
    "IM": {"locale": "en-IM", "timezone": "Europe/Isle_of_Man"},
    "IL": {"locale": "he-IL", "timezone": "Asia/Jerusalem"},
    "IT": {"locale": "it-IT", "timezone": "Europe/Rome"},
    # J
    "JM": {"locale": "en-JM", "timezone": "America/Jamaica"},
    "JP": {"locale": "ja-JP", "timezone": "Asia/Tokyo"},
    "JE": {"locale": "en-JE", "timezone": "Europe/Jersey"},
    "JO": {"locale": "ar-JO", "timezone": "Asia/Amman"},
    # K
    "KZ": {"locale": "kk-KZ", "timezone": "Asia/Almaty"},
    "KE": {"locale": "sw-KE", "timezone": "Africa/Nairobi"},
    "KI": {"locale": "en-KI", "timezone": "Pacific/Tarawa"},
    "KP": {"locale": "ko-KP", "timezone": "Asia/Pyongyang"},
    "KR": {"locale": "ko-KR", "timezone": "Asia/Seoul"},
    "XK": {"locale": "sq-XK", "timezone": "Europe/Belgrade"},
    "KW": {"locale": "ar-KW", "timezone": "Asia/Kuwait"},
    "KG": {"locale": "ky-KG", "timezone": "Asia/Bishkek"},
    # L
    "LA": {"locale": "lo-LA", "timezone": "Asia/Vientiane"},
    "LV": {"locale": "lv-LV", "timezone": "Europe/Riga"},
    "LB": {"locale": "ar-LB", "timezone": "Asia/Beirut"},
    "LS": {"locale": "en-LS", "timezone": "Africa/Maseru"},
    "LR": {"locale": "en-LR", "timezone": "Africa/Monrovia"},
    "LY": {"locale": "ar-LY", "timezone": "Africa/Tripoli"},
    "LI": {"locale": "de-LI", "timezone": "Europe/Vaduz"},
    "LT": {"locale": "lt-LT", "timezone": "Europe/Vilnius"},
    "LU": {"locale": "fr-LU", "timezone": "Europe/Luxembourg"},
    # M
    "MO": {"locale": "zh-MO", "timezone": "Asia/Macau"},
    "MK": {"locale": "mk-MK", "timezone": "Europe/Skopje"},
    "MG": {"locale": "fr-MG", "timezone": "Indian/Antananarivo"},
    "MW": {"locale": "en-MW", "timezone": "Africa/Blantyre"},
    "MY": {"locale": "ms-MY", "timezone": "Asia/Kuala_Lumpur"},
    "MV": {"locale": "dv-MV", "timezone": "Indian/Maldives"},
    "ML": {"locale": "fr-ML", "timezone": "Africa/Bamako"},
    "MT": {"locale": "mt-MT", "timezone": "Europe/Malta"},
    "MH": {"locale": "en-MH", "timezone": "Pacific/Majuro"},
    "MQ": {"locale": "fr-MQ", "timezone": "America/Martinique"},
    "MR": {"locale": "ar-MR", "timezone": "Africa/Nouakchott"},
    "MU": {"locale": "en-MU", "timezone": "Indian/Mauritius"},
    "YT": {"locale": "fr-YT", "timezone": "Indian/Mayotte"},
    "MX": {"locale": "es-MX", "timezone": "America/Mexico_City"},
    "FM": {"locale": "en-FM", "timezone": "Pacific/Pohnpei"},
    "MD": {"locale": "ro-MD", "timezone": "Europe/Chisinau"},
    "MC": {"locale": "fr-MC", "timezone": "Europe/Monaco"},
    "MN": {"locale": "mn-MN", "timezone": "Asia/Ulaanbaatar"},
    "ME": {"locale": "sr-ME", "timezone": "Europe/Podgorica"},
    "MS": {"locale": "en-MS", "timezone": "America/Montserrat"},
    "MA": {"locale": "ar-MA", "timezone": "Africa/Casablanca"},
    "MZ": {"locale": "pt-MZ", "timezone": "Africa/Maputo"},
    "MM": {"locale": "my-MM", "timezone": "Asia/Yangon"},
    # N
    "NA": {"locale": "en-NA", "timezone": "Africa/Windhoek"},
    "NR": {"locale": "en-NR", "timezone": "Pacific/Nauru"},
    "NP": {"locale": "ne-NP", "timezone": "Asia/Kathmandu"},
    "NL": {"locale": "nl-NL", "timezone": "Europe/Amsterdam"},
    "AN": {"locale": "nl-AN", "timezone": "America/Curacao"},
    "NC": {"locale": "fr-NC", "timezone": "Pacific/Noumea"},
    "NZ": {"locale": "en-NZ", "timezone": "Pacific/Auckland"},
    "NI": {"locale": "es-NI", "timezone": "America/Managua"},
    "NE": {"locale": "fr-NE", "timezone": "Africa/Niamey"},
    "NG": {"locale": "en-NG", "timezone": "Africa/Lagos"},
    "NU": {"locale": "en-NU", "timezone": "Pacific/Niue"},
    "NF": {"locale": "en-NF", "timezone": "Pacific/Norfolk"},
    "MP": {"locale": "en-MP", "timezone": "Pacific/Saipan"},
    "NO": {"locale": "no-NO", "timezone": "Europe/Oslo"},
    # O
    "OM": {"locale": "ar-OM", "timezone": "Asia/Muscat"},
    # P
    "PK": {"locale": "ur-PK", "timezone": "Asia/Karachi"},
    "PW": {"locale": "en-PW", "timezone": "Pacific/Palau"},
    "PS": {"locale": "ar-PS", "timezone": "Asia/Gaza"},
    "PA": {"locale": "es-PA", "timezone": "America/Panama"},
    "PG": {"locale": "en-PG", "timezone": "Pacific/Port_Moresby"},
    "PY": {"locale": "es-PY", "timezone": "America/Asuncion"},
    "PE": {"locale": "es-PE", "timezone": "America/Lima"},
    "PH": {"locale": "fil-PH", "timezone": "Asia/Manila"},
    "PN": {"locale": "en-PN", "timezone": "Pacific/Pitcairn"},
    "PL": {"locale": "pl-PL", "timezone": "Europe/Warsaw"},
    "PT": {"locale": "pt-PT", "timezone": "Europe/Lisbon"},
    "PR": {"locale": "es-PR", "timezone": "America/Puerto_Rico"},
    # Q
    "QA": {"locale": "ar-QA", "timezone": "Asia/Qatar"},
    # R
    "RS": {"locale": "sr-RS", "timezone": "Europe/Belgrade"},
    "RE": {"locale": "fr-RE", "timezone": "Indian/Reunion"},
    "RO": {"locale": "ro-RO", "timezone": "Europe/Bucharest"},
    "RU": {"locale": "ru-RU", "timezone": "Europe/Moscow"},
    "RW": {"locale": "rw-RW", "timezone": "Africa/Kigali"},
    # S
    "BL": {"locale": "fr-BL", "timezone": "America/St_Barthelemy"},
    "SH": {"locale": "en-SH", "timezone": "Atlantic/St_Helena"},
    "KN": {"locale": "en-KN", "timezone": "America/St_Kitts"},
    "LC": {"locale": "en-LC", "timezone": "America/St_Lucia"},
    "MF": {"locale": "fr-MF", "timezone": "America/Marigot"},
    "PM": {"locale": "fr-PM", "timezone": "America/Miquelon"},
    "VC": {"locale": "en-VC", "timezone": "America/St_Vincent"},
    "WS": {"locale": "sm-WS", "timezone": "Pacific/Apia"},
    "SM": {"locale": "it-SM", "timezone": "Europe/San_Marino"},
    "ST": {"locale": "pt-ST", "timezone": "Africa/Sao_Tome"},
    "SA": {"locale": "ar-SA", "timezone": "Asia/Riyadh"},
    "SN": {"locale": "fr-SN", "timezone": "Africa/Dakar"},
    "CS": {"locale": "sr-CS", "timezone": "Europe/Belgrade"},
    "SC": {"locale": "fr-SC", "timezone": "Indian/Mahe"},
    "SL": {"locale": "en-SL", "timezone": "Africa/Freetown"},
    "SG": {"locale": "en-SG", "timezone": "Asia/Singapore"},
    "SX": {"locale": "nl-SX", "timezone": "America/Lower_Princes"},
    "SK": {"locale": "sk-SK", "timezone": "Europe/Bratislava"},
    "SI": {"locale": "sl-SI", "timezone": "Europe/Ljubljana"},
    "SB": {"locale": "en-SB", "timezone": "Pacific/Guadalcanal"},
    "SO": {"locale": "so-SO", "timezone": "Africa/Mogadishu"},
    "ZA": {"locale": "en-ZA", "timezone": "Africa/Johannesburg"},
    "GS": {"locale": "en-GS", "timezone": "Atlantic/South_Georgia"},
    "SS": {"locale": "en-SS", "timezone": "Africa/Juba"},
    "ES": {"locale": "es-ES", "timezone": "Europe/Madrid"},
    "LK": {"locale": "si-LK", "timezone": "Asia/Colombo"},
    "SD": {"locale": "ar-SD", "timezone": "Africa/Khartoum"},
    "SR": {"locale": "nl-SR", "timezone": "America/Paramaribo"},
    "SJ": {"locale": "no-SJ", "timezone": "Arctic/Longyearbyen"},
    "SZ": {"locale": "en-SZ", "timezone": "Africa/Mbabane"},
    "SE": {"locale": "sv-SE", "timezone": "Europe/Stockholm"},
    "CH": {"locale": "de-CH", "timezone": "Europe/Zurich"},
    "SY": {"locale": "ar-SY", "timezone": "Asia/Damascus"},
    # T
    "TW": {"locale": "zh-TW", "timezone": "Asia/Taipei"},
    "TJ": {"locale": "tg-TJ", "timezone": "Asia/Dushanbe"},
    "TZ": {"locale": "sw-TZ", "timezone": "Africa/Dar_es_Salaam"},
    "TH": {"locale": "th-TH", "timezone": "Asia/Bangkok"},
    "TL": {"locale": "pt-TL", "timezone": "Asia/Dili"},
    "TG": {"locale": "fr-TG", "timezone": "Africa/Lome"},
    "TK": {"locale": "en-TK", "timezone": "Pacific/Fakaofo"},
    "TO": {"locale": "to-TO", "timezone": "Pacific/Tongatapu"},
    "TT": {"locale": "en-TT", "timezone": "America/Port_of_Spain"},
    "TN": {"locale": "ar-TN", "timezone": "Africa/Tunis"},
    "TR": {"locale": "tr-TR", "timezone": "Europe/Istanbul"},
    "XT": {"locale": "en-XT", "timezone": "UTC"},
    "TM": {"locale": "tk-TM", "timezone": "Asia/Ashgabat"},
    "TC": {"locale": "en-TC", "timezone": "America/Grand_Turk"},
    "TV": {"locale": "en-TV", "timezone": "Pacific/Funafuti"},
    # U
    "UG": {"locale": "en-UG", "timezone": "Africa/Kampala"},
    "UA": {"locale": "uk-UA", "timezone": "Europe/Kyiv"},
    "AE": {"locale": "ar-AE", "timezone": "Asia/Dubai"},
    "GB": {"locale": "en-GB", "timezone": "Europe/London"},
    "US": {"locale": "en-US", "timezone": "America/New_York"},
    "UM": {"locale": "en-UM", "timezone": "Pacific/Wake"},
    "UY": {"locale": "es-UY", "timezone": "America/Montevideo"},
    "UZ": {"locale": "uz-UZ", "timezone": "Asia/Tashkent"},
    # V
    "VU": {"locale": "bi-VU", "timezone": "Pacific/Efate"},
    "VE": {"locale": "es-VE", "timezone": "America/Caracas"},
    "VN": {"locale": "vi-VN", "timezone": "Asia/Ho_Chi_Minh"},
    "VG": {"locale": "en-VG", "timezone": "America/Tortola"},
    "VI": {"locale": "en-VI", "timezone": "America/St_Thomas"},
    # W
    "WF": {"locale": "fr-WF", "timezone": "Pacific/Wallis"},
    "EH": {"locale": "ar-EH", "timezone": "Africa/El_Aaiun"},
    # Y
    "YE": {"locale": "ar-YE", "timezone": "Asia/Aden"},
    # Z
    "ZM": {"locale": "en-ZM", "timezone": "Africa/Lusaka"},
    "ZW": {"locale": "en-ZW", "timezone": "Africa/Harare"},
    # Default fallback
    "DEFAULT": {"locale": "en-US", "timezone": "UTC"},
}
