# coding: utf-8

"""
    Manager

    Subscription management and related services.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from manager_client.models.node_request import NodeRequest

class TestNodeRequest(unittest.TestCase):
    """NodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeRequest:
        """Test NodeRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeRequest`
        """
        model = NodeRequest()
        if include_optional:
            return NodeRequest(
                embeddings = [
                    1.337
                    ],
                entity_id = '',
                metadata = {
                    'key' : None
                    },
                node_id = '',
                text = ''
            )
        else:
            return NodeRequest(
                entity_id = '',
                node_id = '',
        )
        """

    def testNodeRequest(self):
        """Test NodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
