# coding: utf-8

"""
    Manager

    Subscription management and related services.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from manager_client.api.vector_search_queries_api import VectorSearchQueriesApi


class TestVectorSearchQueriesApi(unittest.TestCase):
    """VectorSearchQueriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VectorSearchQueriesApi()

    def tearDown(self) -> None:
        pass

    def test_create_query(self) -> None:
        """Test case for create_query

        Create
        """
        pass


if __name__ == '__main__':
    unittest.main()
