python_test_utils(
    name="test_utils",
)

python_sources()

python_tests(
    name="tests0",
    dependencies=[
        "llama-index-packs/llama-index-packs-koda-retriever/tests/koda_mocking.py",
        "llama-index-packs/llama-index-packs-koda-retriever/tests/monkeypatch.py",
    ],
)
