[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "llama-index-vector-stores-feedo"
version = "0.1.0"
description = "llama-index vector_stores feedo integration"
authors = [{name = "Andrii Shumko", email = "andrii@feedo.ink"}]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = "MIT"
dependencies = [
    "feedo-sdk>=0.1.24",
    "llama-index-core>=0.13.0,<0.15",
]

[dependency-groups]
dev = [
    "ipython==8.10.0",
    "jupyter>=1.0.0,<2",
    "mypy==0.991",
    "pre-commit==3.2.0",
    "pylint==2.15.10",
    "pytest==7.2.1",
    "pytest-asyncio==0.21.0",
    "pytest-mock==3.11.1",
    "ruff==0.11.11",
]

[tool.hatch.build.targets.sdist]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.hatch.build.targets.wheel]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.llamahub]
contains_example = false
import_path = "llama_index.vector_stores.feedo"

[tool.llamahub.class_authors]
FeedoVectorStore = "Ashixi"
