python_tests(
    dependencies=[
        "llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml:poetry",
        "llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py",
        "llama-index-integrations/embeddings/llama-index-embeddings-openai/llama_index/embeddings/openai/base.py",
    ]
)
