python_sources()

python_test_utils(
    name="test_utils",
    dependencies=[
        "llama-index-core/tests/indices/multi_modal/mock_services.py",
        "llama-index-core/tests/mock_utils/mock_predict.py",
        "llama-index-core/tests/mock_utils/mock_text_splitter.py",
        "llama-index-core/tests/mock_utils/mock_utils.py",
        "llama-index-core/tests/mock_utils/mock_prompts.py",
    ],
)

python_tests(
    name="tests",
)
