load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "falkordb",
    srcs = ["falkordb.py"],
    deps = [
        "//llama_index/core:base",
        "//llama_index/core/vector_stores:types",
    ],
    visibility = ["//visibility:public"],
)
