"""DeepInfra API base URL."""

API_BASE = "https://api.deepinfra.com"
"""DeepInfra Inference API endpoint."""
INFERENCE_ENDPOINT = "v1/openai/completions"
"""Chat API endpoint for DeepInfra."""
CHAT_API_ENDPOINT = "v1/openai/chat/completions"
"""Environment variable name of DeepInfra API token."""
ENV_VARIABLE = "DEEPINFRA_API_TOKEN"
"""Default model name for DeepInfra embeddings."""
DEFAULT_MODEL_NAME = "mistralai/Mixtral-8x22B-Instruct-v0.1"
"""Default max tokens. DeepInfra documentation constant is set."""
DEFAULT_MAX_TOKENS = 512
"""Tool choice is auto."""
TOOL_CHOICE = "auto"
"""User agent"""
USER_AGENT = "llama-index-llms-deepinfra"
