# This file was auto-generated by Fern from our API Definition.

import typing

from .entity_extractor import EntityExtractor
from .hierarchical_node_parser import HierarchicalNodeParser
from .hugging_face_embedding import HuggingFaceEmbedding
from .keyword_extractor import KeywordExtractor
from .marvin_metadata_extractor import MarvinMetadataExtractor
from .open_ai_embedding import OpenAiEmbedding
from .questions_answered_extractor import QuestionsAnsweredExtractor
from .sentence_window_node_parser import SentenceWindowNodeParser
from .simple_node_parser import SimpleNodeParser
from .summary_extractor import SummaryExtractor
from .title_extractor import TitleExtractor

ConfiguredTransformationItemComponentOne = typing.Union[
    KeywordExtractor,
    TitleExtractor,
    EntityExtractor,
    MarvinMetadataExtractor,
    SummaryExtractor,
    QuestionsAnsweredExtractor,
    SimpleNodeParser,
    SentenceWindowNodeParser,
    HierarchicalNodeParser,
    OpenAiEmbedding,
    HuggingFaceEmbedding,
]
