# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from llama_index.bridge.pydantic import pydantic

from ..core.datetime_utils import serialize_datetime
from .metadata_extractor import MetadataExtractor


class SentenceWindowNodeParser(pydantic.BaseModel):
    """
    Sentence window node parser.

    Splits a document into Nodes, with each node being a sentence.
    Each node contains a window from the surrounding sentences in the metadata.

    Args:
        sentence_splitter (Optional[Callable]): splits text into sentences
        include_metadata (bool): whether to include metadata in nodes
        include_prev_next_rel (bool): whether to include prev/next relationships
    """

    window_size: typing.Optional[int] = pydantic.Field(
        description="The number of sentences on each side of a sentence to capture."
    )
    window_metadata_key: typing.Optional[str] = pydantic.Field(
        description="The metadata key to store the sentence window under."
    )
    original_text_metadata_key: typing.Optional[str] = pydantic.Field(
        description="The metadata key to store the original sentence in."
    )
    include_metadata: typing.Optional[bool] = pydantic.Field(
        description="Whether or not to consider metadata when splitting."
    )
    include_prev_next_rel: typing.Optional[bool] = pydantic.Field(
        description="Include prev/next node relationships."
    )
    metadata_extractor: typing.Optional[MetadataExtractor] = pydantic.Field(
        description="Metadata extraction pipeline to apply to nodes."
    )
    callback_manager: typing.Optional[typing.Dict[str, typing.Any]]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {
            "by_alias": True,
            "exclude_unset": True,
            **kwargs,
        }
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {
            "by_alias": True,
            "exclude_unset": True,
            **kwargs,
        }
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
