python_tests()

python_requirement(
    name="s3fs",
    requirements=["s3fs>=2024.3.0"],
)

python_requirement(
    name="llama-index-readers-file",
    requirements=["llama-index-readers-file>=0.1.11"],
)
