python_tests(
    name="tests",
    dependencies=["llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/__init__.py"]
)

python_requirement(
    name="s3fs",
    requirements=["s3fs>=2024.3.0"],
)
