DEFAULT_EXTRACT_ELEMENTS_TIMEOUT_SECONDS = 300
DEFAULT_EXTRACT_DATA_TIMEOUT_SECONDS = 900
DEFAULT_WAIT_FOR_NETWORK_IDLE = True
DEFAULT_INCLUDE_HIDDEN_DATA = True
DEFAULT_INCLUDE_HIDDEN_ELEMENTS = False
DEFAULT_RESPONSE_MODE = "fast"

DEFAULT_ENABLE_STEALTH_MODE = False
DEFAULT_WAIT_FOR_PAGE_LOAD = 0
DEFAULT_SCROLL_TO_BOTTOM = False
DEFAULT_SCREENSHOT_ENABLED = False

API_TIMEOUT_SECONDS = 900
