name: Test repo scripts

on:
  push:
    branches:
      - main
    paths:
      - "scripts/**"
  pull_request:
    paths:
      - "scripts/**"

jobs:
  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Run tests
        run: uv run -- python -m pytest scripts/tests/test_run_ci_tests.py
